# Generated by Django 5.1.1 on 2024-10-02 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('duration', models.IntegerField()),
                ('ratio', models.DecimalField(decimal_places=3, max_digits=4)),
            ],
        ),
    ]
