# Generated by Django 5.1.1 on 2024-09-23 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_ads_property_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='property_ids',
        ),
    ]
