# Generated by Django 5.1.1 on 2024-09-23 03:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=25, unique=True)),
                ('image', models.ImageField(upload_to='user/images/profile/')),
                ('email', models.CharField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('password', models.CharField(max_length=50)),
                ('country', models.CharField(choices=[('SA', 'Saudi Arabia'), ('AE', 'United Arab Emirates'), ('EG', 'Egypt'), ('IQ', 'Iraq'), ('JO', 'Jordan'), ('MA', 'Morocco'), ('KW', 'Kuwait'), ('QA', 'Qatar'), ('OM', 'Oman'), ('DZ', 'Algeria')], max_length=2)),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=11)),
                ('register_photo', models.ImageField(upload_to='user/images/register/')),
                ('is_company', models.BooleanField()),
            ],
        ),
    ]
