# Generated by Django 5.1.1 on 2024-10-07 07:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=25, unique=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='user/images/profile/')),
                ('email', models.CharField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('password', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(8)])),
                ('city', models.CharField(blank=True, max_length=25, null=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('street', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('address', models.TextField(blank=True, default='', null=True)),
                ('phone', models.CharField(max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11)])),
                ('another_phone', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.MinLengthValidator(11)])),
                ('register_photo', models.ImageField(blank=True, null=True, upload_to='user/images/register/')),
                ('is_company', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_member', models.BooleanField(default=False)),
            ],
        ),
    ]
