# Generated by Django 5.1.1 on 2024-10-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('data', models.JSONField(blank=True)),
            ],
        ),
    ]
