# Generated by Django 5.1.1 on 2024-10-05 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_property_user_id'),
        ('user', '0002_user_is_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='property_ids',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='property.property'),
        ),
    ]
