# Generated by Django 5.1.1 on 2024-10-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_wish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
