# Generated by Django 5.1.1 on 2024-10-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_wish_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='property_id',
        ),
        migrations.AlterField(
            model_name='wish',
            name='data',
            field=models.JSONField(blank=True, default=[], null=True),
        ),
    ]
