# Generated by Django 5.1.1 on 2024-10-05 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_alter_property_user_id'),
        ('user', '0003_alter_user_property_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='property_ids',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='property.property'),
        ),
    ]
