# Generated by Django 5.1.1 on 2024-09-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='another_phone',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(choices=[('EG', 'Egypt')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to='user/images/profile/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_company',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='register_photo',
            field=models.ImageField(null=True, upload_to='user/images/register/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='street',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
    ]
