# Generated by Django 5.1.1 on 2024-10-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_wish_property_id_alter_wish_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='property_ids',
            field=models.JSONField(blank=True, default=[], null=True),
        ),
    ]
