# Generated by Django 5.1.1 on 2024-10-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_wish_property_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wish',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
