# Generated by Django 5.1.1 on 2024-09-25 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_propertyimage'),
        ('user', '0005_alter_user_address_alter_user_another_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='property_ids',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='property.property'),
        ),
    ]
