# Generated by Django 5.1.1 on 2024-10-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='member_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='member_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
