# Generated by Django 5.1.1 on 2024-09-27 00:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_propertyimage'),
        ('user', '0008_user_address_user_another_phone_user_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='another_phone',
            field=models.CharField(max_length=11, null=True, validators=[django.core.validators.MinLengthValidator(11)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(choices=[('EG', 'Egypt')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to='user/images/profile/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_company',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='property_ids',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='property.property'),
        ),
        migrations.AlterField(
            model_name='user',
            name='register_photo',
            field=models.ImageField(null=True, upload_to='user/images/register/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='street',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=25, unique=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
