# Generated by Django 5.1.1 on 2024-10-12 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_member_duration_user_member_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='member_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
