# Generated by Django 5.1.1 on 2024-10-10 14:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ads', '0001_initial'),
        ('user', '0006_user_wish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5)])),
                ('description', models.TextField()),
                ('property_type', models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial')], max_length=11)),
                ('price', models.IntegerField()),
                ('is_published', models.BooleanField(default=False)),
                ('bed', models.IntegerField(default=1, null=True)),
                ('bath', models.IntegerField(default=1, null=True)),
                ('location', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(10)])),
                ('listed_date', models.DateTimeField(auto_now_add=True)),
                ('country', models.CharField(choices=[('Egypt', 'Egypt')], max_length=5)),
                ('governorate', models.CharField(choices=[('Cairo', 'Cairo'), ('Alexandria', 'Alexandria'), ('Giza', 'Giza'), ('Qalyubia', 'Qalyubia'), ('Dakahlia', 'Dakahlia'), ('Sharqia', 'Sharqia'), ('Gharbia', 'Gharbia'), ('Monufia', 'Monufia'), ('Kafr El Sheikh', 'Kafr El Sheikh'), ('Damietta', 'Damietta'), ('Port Said', 'Port Said'), ('Ismailia', 'Ismailia'), ('Suez', 'Suez'), ('Aswan', 'Aswan'), ('Luxor', 'Luxor'), ('Red Sea', 'Red Sea'), ('Matrouh', 'Matrouh'), ('North Sinai', 'North Sinai'), ('South Sinai', 'South Sinai'), ('Faiyum', 'Faiyum'), ('Beni Suef', 'Beni Suef'), ('Minya', 'Minya'), ('Assiut', 'Assiut'), ('Sohag', 'Sohag'), ('Qena', 'Qena'), ('New Valley', 'New Valley'), ('Damietta', 'Damietta')], max_length=20)),
                ('city', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(4)])),
                ('street', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5)])),
                ('commercial', models.CharField(choices=[('Office', 'Office'), ('Retail', 'Retail'), ('Restaurant', 'Restaurant'), ('Pharmacy', 'Pharmacy'), ('Clinic', 'Clinic'), ('Commercial Building', 'Commercial Building'), ('Commercial Land', 'Commercial Land'), ('Agricultural', 'Agricultural'), ('Warehouse', 'Warehouse'), ('Garage', 'Garage'), ('Other Commercial', 'Other Commercial')], max_length=20)),
                ('is_sale', models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], default='sale', max_length=4)),
                ('area', models.DecimalField(decimal_places=1, max_digits=7)),
                ('image', models.ImageField(upload_to='property/images')),
                ('ads_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_ids', to='ads.ads')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='properties', to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property/images')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='property.property')),
            ],
        ),
    ]
