# Generated by Django 5.1.1 on 2024-10-11 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
        ('user', '0008_user_member_duration_user_member_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='user.user'),
        ),
    ]
