# Generated by Django 5.1.1 on 2024-10-05 10:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='commercial',
            field=models.CharField(choices=[('office', 'Office'), ('retail', 'Retail'), ('restaurant', 'Restaurant'), ('pharmacy', 'Pharmacy'), ('clinic', 'Clinic'), ('commercial building', 'Commercial Building'), ('commercial land', 'Commercial Land'), ('agricultural', 'Agricultural'), ('warehouse', 'Warehouse'), ('other commercial', 'Other Commercial'), ('garage', 'Garage')], max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_sale',
            field=models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], default='sale', max_length=4),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='street',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
