# Generated by Django 5.1.1 on 2024-10-05 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_property_area_alter_property_city_and_more'),
        ('user', '0002_user_is_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='user_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='user.user'),
            preserve_default=False,
        ),
    ]
