# Generated by Django 5.1.1 on 2024-10-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_property_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='listed_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
