# Generated by Django 5.1.1 on 2024-09-23 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property_property_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='property_id',
            new_name='ads_id',
        ),
    ]
