# Generated by Django 3.2.25 on 2024-09-29 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_remove_ads_property_ids'),
        ('property', '0004_propertyimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='ads_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_ids', to='ads.ads'),
        ),
    ]
