# Generated by Django 5.1.1 on 2024-10-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_alter_property_commercial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='is_sale',
            field=models.CharField(choices=[('Sale', 'Sale'), ('Rent', 'Rent')], default='Sale', max_length=4),
        ),
    ]
