# Generated by Django 5.1.1 on 2024-10-05 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_alter_property_user_id'),
        ('user', '0004_alter_user_property_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='properties', to='user.user'),
        ),
    ]
