# Generated by Django 3.2.25 on 2024-09-29 09:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_alter_property_ads_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
