# Generated by Django 5.1.1 on 2024-10-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_alter_property_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.DecimalField(decimal_places=1, max_digits=7),
        ),
        migrations.AlterField(
            model_name='property',
            name='country',
            field=models.CharField(choices=[('Egypt', 'Egypt')], max_length=5),
        ),
    ]
