# Generated by Django 5.1.1 on 2024-10-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_alter_property_area_alter_property_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='commercial',
            field=models.CharField(choices=[('Office', 'Office'), ('Retail', 'Retail'), ('Restaurant', 'Restaurant'), ('Pharmacy', 'Pharmacy'), ('Clinic', 'Clinic'), ('Commercial Building', 'Commercial Building'), ('Commercial Land', 'Commercial Land'), ('Agricultural', 'Agricultural'), ('Warehouse', 'Warehouse'), ('Garage', 'Garage'), ('Other Commercial', 'Other Commercial')], max_length=20),
        ),
    ]
