# Generated by Django 5.1.1 on 2024-10-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_alter_property_commercial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial')], max_length=11),
        ),
    ]
